# Generated by Django 3.2.7 on 2021-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fake_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Percentage', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
