# Generated by Django 3.2.7 on 2021-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fake_students',
            name='MobNo',
            field=models.IntegerField(default=12),
        ),
    ]
