# Generated by Django 3.2.7 on 2021-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeData', '0002_fake_students_mobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake_students',
            name='MobNo',
            field=models.IntegerField(default=0),
        ),
    ]
