# Generated by Django 3.2.7 on 2021-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeData', '0004_rename_mobno_fake_students_mobnom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fake_students',
            name='MobNom',
        ),
        migrations.AddField(
            model_name='fake_students',
            name='MobNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
